CREATE TABLE COURSES (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(20) NOT NULL,
    rating INT NOT NULL,
    description VARCHAR(1000) NOT NULL
);